services:
  hooore-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=dashboard
        - PORT=${PORT}
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    env_file:
      - path: ./.env
        required: true
    depends_on:
      hooore-dashboard:
        condition: service_healthy
    extra_hosts:
      - host.docker.internal:host-gateway
