services:
  hooore-generator-listener:
    image: hooore-generator-listener
    build:
      context: ../../
      dockerfile: Dockerfile.server
      args:
        - APP_NAME=generator-listener
        - PG_URL=${PG_URL}
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "${PORT}:${PORT}"
